const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  PATIENT: 'PATIENT',
});

const USER_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
});

const DOCTOR_VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

const CONSULTATION_MODES = Object.freeze({
  FACE_TO_FACE: 'FACE_TO_FACE',
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
});

const APPOINTMENT_STATUS = Object.freeze({
  HELD: 'HELD',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  RESCHEDULED: 'RESCHEDULED',
});

const PAYMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
});

const CONSULTATION_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  WAITING: 'WAITING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  INTERRUPTED: 'INTERRUPTED',
  CANCELLED: 'CANCELLED',
});

const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  ADMIN_UPDATED_SETTINGS: 'ADMIN_UPDATED_SETTINGS',
  DOCTOR_VERIFICATION_SUBMITTED: 'DOCTOR_VERIFICATION_SUBMITTED',
  DOCTOR_APPROVED: 'DOCTOR_APPROVED',
  DOCTOR_REJECTED: 'DOCTOR_REJECTED',
  DOCTOR_SUSPENDED: 'DOCTOR_SUSPENDED',
  PATIENT_RECORD_UPLOADED: 'PATIENT_RECORD_UPLOADED',
  PATIENT_RECORD_VIEWED: 'PATIENT_RECORD_VIEWED',
  PATIENT_RECORD_DOWNLOADED: 'PATIENT_RECORD_DOWNLOADED',
  PATIENT_RECORD_DELETED: 'PATIENT_RECORD_DELETED',
  APPOINTMENT_HELD: 'APPOINTMENT_HELD',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  PAYMENT_ORDER_CREATED: 'PAYMENT_ORDER_CREATED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  ADMIN_DOCTOR_CREATED: 'ADMIN_DOCTOR_CREATED',
  ADMIN_DOCTOR_UPDATED: 'ADMIN_DOCTOR_UPDATED',
  ADMIN_DOCTOR_DELETED: 'ADMIN_DOCTOR_DELETED',
  ADMIN_BULK_DOCTORS_CREATED: 'ADMIN_BULK_DOCTORS_CREATED',
  ADMIN_PATIENT_CREATED: 'ADMIN_PATIENT_CREATED',
  ADMIN_PATIENT_UPDATED: 'ADMIN_PATIENT_UPDATED',
  ADMIN_PATIENT_DELETED: 'ADMIN_PATIENT_DELETED',
  ADMIN_BULK_PATIENTS_CREATED: 'ADMIN_BULK_PATIENTS_CREATED',
  ADMIN_APPOINTMENT_CREATED: 'ADMIN_APPOINTMENT_CREATED',
  ADMIN_APPOINTMENT_MODIFIED: 'ADMIN_APPOINTMENT_MODIFIED',
  ADMIN_APPOINTMENT_DELETED: 'ADMIN_APPOINTMENT_DELETED',
  ADMIN_PAYMENT_MODIFIED: 'ADMIN_PAYMENT_MODIFIED',
});

module.exports = {
  ROLES,
  USER_STATUS,
  DOCTOR_VERIFICATION_STATUS,
  CONSULTATION_MODES,
  APPOINTMENT_STATUS,
  PAYMENT_STATUS,
  CONSULTATION_STATUS,
  AUDIT_ACTIONS,
};
