const test = require('node:test');
const assert = require('node:assert/strict');
const request = require('supertest');
const app = require('../../app');
const config = require('../../config');
const db = require('../../config/database');

test.describe('Integration Tests: Patient & Admin End-to-End Business Flow', () => {
  const origAuthMode = config.auth.mode;

  test.before(() => {
    config.auth.mode = 'test';
  });

  test.after(async () => {
    config.auth.mode = origAuthMode;
    await db.end();
  });

  test('1. Patient browses departments populated in MySQL database', async () => {
    const res = await request(app)
      .get('/api/v1/patient/departments')
      .set('x-test-user-id', '3'); // Patient

    assert.equal(res.status, 200);
    assert.equal(res.body.success, true);
    assert.ok(Array.isArray(res.body.data));
    assert.ok(res.body.data.length >= 8); // Seeded departments
    const deptNames = res.body.data.map(d => d.name);
    assert.ok(deptNames.includes('General Medicine'));
    assert.ok(deptNames.includes('Cardiology'));
  });

  test('2. Patient updates health vitals and checks database persistence', async () => {
    const res = await request(app)
      .patch('/api/v1/patient/profile')
      .set('x-test-user-id', '3')
      .send({
        name: 'Rahul Verma Updated',
        height_cm: 180.0,
        weight_kg: 75.5,
      });

    assert.equal(res.status, 200);
    assert.equal(res.body.success, true);

    // Verify in database
    const [rows] = await db.query('SELECT name, height_cm, weight_kg FROM patients WHERE user_id = ?', [3]);
    assert.equal(rows.length, 1);
    assert.equal(rows[0].name, 'Rahul Verma Updated');
    assert.equal(Number(rows[0].height_cm), 180.0);
    assert.equal(Number(rows[0].weight_kg), 75.5);
  });

  test('3. Admin retrieves platform configuration from platform_settings table', async () => {
    const res = await request(app)
      .get('/api/v1/admin/settings')
      .set('x-test-user-id', '1'); // Admin

    assert.equal(res.status, 200);
    assert.equal(res.body.success, true);
    assert.ok(res.body.data);
    assert.ok(typeof res.body.data.platform_fee !== 'undefined');
  });

  test('4. Admin updates platform fee, and database records change', async () => {
    const newFee = 149.00;
    const patchRes = await request(app)
      .patch('/api/v1/admin/settings')
      .set('x-test-user-id', '1')
      .send({
        platformFee: newFee,
      });

    assert.equal(patchRes.status, 200);
    assert.equal(patchRes.body.success, true);

    // Verify from DB
    const [rows] = await db.query('SELECT platform_fee FROM platform_settings WHERE active = 1 ORDER BY id DESC LIMIT 1');
    assert.equal(Number(rows[0].platform_fee), newFee);
  });

  test('5. Admin fetches system dashboard aggregate metrics from DB', async () => {
    const res = await request(app)
      .get('/api/v1/admin/dashboard')
      .set('x-test-user-id', '1');

    assert.equal(res.status, 200);
    assert.equal(res.body.success, true);
    assert.ok(res.body.data);
    assert.ok(typeof res.body.data.doctors.total === 'number');
    assert.ok(typeof res.body.data.patients.total === 'number');
    assert.ok(typeof res.body.data.revenue !== 'undefined');
  });

  test('6. Admin inspects audit logs generated by system actions', async () => {
    const res = await request(app)
      .get('/api/v1/admin/audit-logs')
      .set('x-test-user-id', '1');

    assert.equal(res.status, 200);
    assert.equal(res.body.success, true);
    assert.ok(res.body.data);
    assert.ok(Array.isArray(res.body.data.items));
  });
});
